# Generated by Django 6.0 on 2026-01-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_member_constituency_member_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_coordinator_applicant',
            field=models.BooleanField(default=False),
        ),
    ]
