# Generated by Django 6.0 on 2026-01-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_member_is_coordinator_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorApplicant',
            fields=[
            ],
            options={
                'verbose_name': 'Coordinator Applicant',
                'verbose_name_plural': 'Coordinator Applicants',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.member',),
        ),
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_coordinator_applicant',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
