# Generated by Django 5.2.10 on 2026-02-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_coordinatorapplicant_alter_member_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='constituency',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
