# Generated by Django 5.2.10 on 2026-02-11 22:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_member_constituency_alter_member_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
