# Generated by Django 5.2.10 on 2026-02-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_member_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_card',
            field=models.FileField(blank=True, null=True, upload_to='member_cards/'),
        ),
    ]
