# Generated by Django 6.0 on 2026-01-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g. Party Leader, Deputy Party Leader', max_length=100)),
                ('nickname', models.CharField(blank=True, help_text='e.g. The Fifth', max_length=100)),
                ('image', models.ImageField(upload_to='leaders/')),
                ('order', models.IntegerField(default=0, help_text='Higher number = earlier in list')),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
    ]
