# Generated by Django 6.0 on 2026-01-01 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL friendly name, e.g. legalize-marijuana', unique=True)),
                ('icon', models.CharField(help_text='Emoji icon, e.g. 🌿', max_length=10)),
                ('summary', models.TextField(help_text='Short description for the main list.')),
                ('description', models.TextField(help_text='Detailed description for the detail page.')),
                ('local_impact', models.TextField(blank=True, help_text='Impact on Kenya.')),
                ('target_revenue', models.CharField(blank=True, help_text='Optional revenue text highlight', max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ManifestoEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='core.manifestoitem')),
            ],
        ),
    ]
