# Generated by Django 6.0 on 2026-01-01 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_gallerypost_postimage_delete_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='bio',
            field=models.TextField(blank=True, help_text='Detailed biography.'),
        ),
        migrations.AddField(
            model_name='leader',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL friendly name, e.g. george-wajackoyah'),
        ),
        migrations.AddField(
            model_name='leader',
            name='twitter_handle',
            field=models.CharField(blank=True, help_text='@username', max_length=100),
        ),
        migrations.CreateModel(
            name='LeaderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='leaders/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.leader')),
            ],
        ),
    ]
