# Generated by Django 6.0 on 2026-01-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_leader_bio_leader_slug_leader_twitter_handle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL friendly name, e.g. george-wajackoyah', unique=True),
        ),
    ]
