# Generated by Django 6.0 on 2026-01-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestoevidence',
            name='annual_revenue',
            field=models.CharField(blank=True, help_text='Annual cannabis revenue in Ksh', max_length=100),
        ),
        migrations.AddField(
            model_name='manifestoevidence',
            name='detailed_history',
            field=models.TextField(blank=True, help_text='Comprehensive legalization history'),
        ),
        migrations.AddField(
            model_name='manifestoevidence',
            name='economic_impact',
            field=models.TextField(blank=True, help_text='Economic effects and statistics'),
        ),
        migrations.AddField(
            model_name='manifestoevidence',
            name='flag_emoji',
            field=models.CharField(blank=True, help_text='Country flag emoji', max_length=10),
        ),
        migrations.AddField(
            model_name='manifestoevidence',
            name='lessons_for_kenya',
            field=models.TextField(blank=True, help_text='What Kenya can learn'),
        ),
        migrations.AddField(
            model_name='manifestoevidence',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly country name'),
        ),
        migrations.AddField(
            model_name='manifestoevidence',
            name='timeline',
            field=models.TextField(blank=True, help_text='Key dates and milestones in JSON format'),
        ),
    ]
