# Generated by Django 6.0 on 2026-01-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('news', 'Party News'), ('press', 'Press Release'), ('campaign', 'Campaign Update'), ('policy', 'Policy Announcement'), ('event', 'Event Recap'), ('opinion', 'Opinion')], default='news', max_length=20)),
                ('excerpt', models.TextField(help_text='Short summary for list views', max_length=300)),
                ('content', models.TextField(help_text='Full article content (supports markdown)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('author', models.CharField(default='Roots Party Media', max_length=100)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_published', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text='County code e.g. 001', max_length=10)),
                ('presence_status', models.CharField(choices=[('active', 'Active - Full Operations'), ('growing', 'Growing - Establishing Presence'), ('starting', 'Starting - Initial Contact'), ('planned', 'Planned - Not Yet Started')], default='planned', max_length=20)),
                ('coordinator_name', models.CharField(blank=True, max_length=100)),
                ('coordinator_phone', models.CharField(blank=True, max_length=20)),
                ('members_count', models.PositiveIntegerField(default=0)),
                ('offices_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
                'ordering': ['name'],
            },
        ),
    ]
