# Generated by Django 6.0 on 2026-01-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_blogpost_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (MP4, etc.)', null=True, upload_to='blog/videos/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo URL', null=True),
        ),
    ]
