# Generated by Django 6.0 on 2026-01-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='kpi_value',
            field=models.IntegerField(blank=True, help_text='Optional override for main stat (e.g. Member Count)', null=True),
        ),
    ]
