# Generated by Django 6.0 on 2026-01-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pagecontent_kpi_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='county',
            name='notes',
            field=models.TextField(blank=True, help_text='Economic plans and other notes'),
        ),
    ]
