# Generated by Django 6.0 on 2026-01-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_county_slug_alter_county_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='slug',
            field=models.SlugField(blank=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
