# Generated by Django 6.0 on 2026-01-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_county_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='description',
            field=models.TextField(blank=True, help_text='General introduction about the county'),
        ),
        migrations.AddField(
            model_name='county',
            name='image',
            field=models.ImageField(blank=True, help_text='Header image for the county page', null=True, upload_to='counties/'),
        ),
        migrations.AlterField(
            model_name='county',
            name='notes',
            field=models.TextField(blank=True, help_text='Detailed economic revolution plan', verbose_name='Economic Plan'),
        ),
    ]
