# Generated by Django 6.0 on 2026-01-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_county_description_county_image_alter_county_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Watch The Message', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short description or quote')),
                ('video_file', models.FileField(blank=True, help_text='Upload a video file (MP4)', null=True, upload_to='videos/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL (overrides uploaded file)', null=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Cover image for the video', null=True, upload_to='videos/thumbnails/')),
                ('button_text', models.CharField(default='View More Videos', help_text='Text for the call-to-action button', max_length=50)),
                ('button_url', models.CharField(default='/gallery/', help_text='URL for the button', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active video will be shown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Home Video',
                'verbose_name_plural': 'Home Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
