# Generated by Django 6.0 on 2026-01-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_homevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gate_pass_downloads',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the gate pass has been downloaded'),
        ),
    ]
