# Generated by Django 6.0 on 2026-01-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_vendor_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified/Official Roots Party vendor'),
        ),
    ]
