# Generated by Django 6.0 on 2026-01-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL identifier e.g. president, governor', unique=True)),
                ('icon_svg_path', models.TextField(help_text='Paste the SVG path data (d attribute) here')),
                ('description', models.TextField(help_text='Main role description')),
                ('responsibilities', models.TextField(help_text='Enter each responsibility on a new line')),
                ('roots_context', models.TextField(help_text='The Roots Mandate for this role')),
                ('prospects', models.TextField(blank=True, help_text='Why a Roots Government? Enter each point on a new line')),
                ('candidate_name', models.CharField(blank=True, help_text='Name of the current candidate/holder', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Candidate photo', null=True, upload_to='leadership/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo link for candidate message', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
