# Generated by Django 6.0 on 2026-01-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_leadershiprole'),
    ]

    operations = [
    ]
