# Generated by Django for populating comprehensive cannabis country data

from django.db import migrations


def populate_country_data(apps, schema_editor):
    ManifestoEvidence = apps.get_model('core', 'ManifestoEvidence')
    
    country_data = {
        'canada': {
            'detailed_history': """Canada's journey to cannabis legalization was decades in the making. The Cannabis Act (Bill C-45) received Royal Assent on June 21, 2018, making Canada the second country in the world (after Uruguay) to fully legalize recreational cannabis nationwide.

The path began in the 1970s when the Le Dain Commission first recommended decriminalization. In 2001, Canada became one of the first countries to legalize medical cannabis. The Liberal Party, led by Justin Trudeau, made recreational legalization a key campaign promise in 2015.

The legislation allows adults 18+ (19+ in some provinces) to possess up to 30 grams in public, grow up to 4 plants per household, and purchase from licensed retailers. Each province regulates its own distribution system.""",
            
            'timeline': """• 1923: Cannabis added to schedule of restricted drugs
• 1961: Criminalized under Narcotics Control Act
• 1972: Le Dain Commission recommends decriminalization
• 2001: Medical cannabis legalized (MMAR program)
• 2013: Medical program reforms (MMPR/ACMPR)
• 2015: Liberal Party wins election on legalization platform
• 2017: Bill C-45 (Cannabis Act) introduced
• June 2018: Cannabis Act receives Royal Assent
• October 17, 2018: Recreational sales begin
• October 2019: Cannabis 2.0 - edibles, extracts legalized""",
            
            'economic_impact': """• $43.5 billion CAD in total sales since legalization (2018-2023)
• C$4.3 billion in annual sales by 2023
• Over 151,000 direct jobs created in the industry
• C$15.1 billion contributed to GDP (2022)
• C$3.3 billion in tax revenue collected (federal/provincial)
• 97% of cannabis consumed now comes from legal sources
• Illicit market reduced from 90% to under 40% of market share
• 3,500+ licensed retail stores across the country
• Stock market valuations exceeded C$50 billion at peak""",
            
            'lessons_for_kenya': """1. GRADUAL ROLLOUT: Canada started with dried flower only, adding edibles/extracts a year later. Kenya could phase in products similarly.

2. PROVINCIAL FLEXIBILITY: Each province customized regulations (age limits, store ownership). Kenya's county governments could have similar flexibility.

3. SUPPLY CHAIN READINESS: Early shortages showed importance of licensed cultivation capacity before retail launch. Kenya should build supply first.

4. PRICE COMPETITIVENESS: Legal prices must beat black market. Canada learned to reduce taxes and regulations to compete.

5. INDIGENOUS INVOLVEMENT: First Nations communities gained economic opportunities. Kenya could similarly empower farming communities.

6. PUBLIC EDUCATION: Extensive campaigns on responsible use, impaired driving. Essential for Kenya's transition.""",
            
            'annual_revenue': 'C$4.3 Billion (2023)'
        },
        
        'usa-colorado': {
            'detailed_history': """Colorado became the first U.S. state to legalize recreational cannabis when voters approved Amendment 64 on November 6, 2012. The measure passed with 55% support, making it legal for adults 21+ to possess up to one ounce.

Retail sales began January 1, 2014, making Colorado a testing ground for American cannabis policy. The state had already legalized medical cannabis in 2000 (Amendment 20), building regulatory experience.

Governor John Hickenlooper, initially opposed, implemented a robust regulatory framework that became a model for other states. The Colorado Department of Revenue's Marijuana Enforcement Division oversees all licensing and enforcement.""",
            
            'timeline': """• 2000: Amendment 20 legalizes medical cannabis
• 2010: Medical dispensary regulations established
• November 2012: Amendment 64 passes (55% yes)
• December 2012: Governor signs Amendment 64
• January 1, 2014: First recreational sales
• 2016: Over $1 billion in annual sales
• 2019: $1.7 billion in sales
• 2020: $2.2 billion in sales (pandemic boost)
• 2021: Record $2.2 billion in sales
• 2023: Market stabilizes at ~$1.5 billion""",
            
            'economic_impact': """• $15+ billion in total sales since 2014
• $2.2 billion in tax revenue collected (2014-2023)
• Peak of $423 million tax revenue in single year (2021)
• Over 44,000 licensed industry workers
• 2,900+ licensed cannabis businesses
• $40 million annually to school construction (BEST program)
• Property values increased near dispensaries
• Tourism boost: "cannabis tourism" industry emerged
• Reduced arrests: 90% drop in cannabis-related arrests
• Savings of $40-60 million annually in enforcement costs""",
            
            'lessons_for_kenya': """1. LOCAL CONTROL: Counties can ban or allow retail. Kenya could let counties opt-in or opt-out.

2. TAX STRUCTURE: Colorado's 15% excise + sales tax generates revenue while allowing competition with black market. Keep taxes reasonable.

3. REVENUE EARMARKING: Funds go to specific programs (schools, health, local governments). Kenya could direct revenue to youth employment, healthcare.

4. SEED-TO-SALE TRACKING: METRC system tracks all legal cannabis. Essential for preventing diversion. Kenya needs similar technology.

5. BANKING SOLUTIONS: Despite federal issues, Colorado created state-backed solutions. Kenya can integrate with M-Pesa/mobile money.

6. SOCIAL EQUITY: Colorado added programs to help communities harmed by prohibition. Kenya should include expungement and business opportunities.""",
            
            'annual_revenue': '$423 Million peak (2021)'
        },
        
        'israel': {
            'detailed_history': """Israel is a global leader in cannabis research, with pioneering work dating to the 1960s. Professor Raphael Mechoulam at Hebrew University discovered THC in 1964 and later identified the endocannabinoid system, earning him the title "Father of Cannabis Research."

Medical cannabis was legalized in 1999, making Israel one of the earliest adopters. The program expanded significantly under the Israel Medical Cannabis Agency (IMCA) established in 2007. By 2023, over 120,000 patients have medical cannabis licenses.

While recreational use remains illegal, Israel decriminalized possession in 2019. The country is positioned as a hub for cannabis research, technology, and export.""",
            
            'timeline': """• 1964: Prof. Mechoulam isolates THC at Hebrew University
• 1992: Endocannabinoid system discovered (anandamide)
• 1999: Medical cannabis program begins
• 2007: Israel Medical Cannabis Agency (IMCA) established
• 2016: Government approves export of medical cannabis
• 2017: First commercial medical cannabis farms licensed
• 2019: Possession decriminalized (fine instead of arrest)
• 2021: 100,000+ medical cannabis patients
• 2022: Export begins to Europe
• 2023: 120,000+ patients, major export industry""",
            
            'economic_impact': """• $300+ million domestic medical cannabis market
• Projected $1 billion+ export industry by 2025
• Over 100 cannabis-focused research studies underway
• 50+ cannabis startups and tech companies
• Leading in cannabis pharmaceutical development
• Major export destinations: Germany, UK, Australia
• 8 licensed producers with GMP certification
• Attracts international pharma investments
• Medical tourism for cannabis treatment
• World's highest per-capita medical cannabis use""",
            
            'lessons_for_kenya': """1. RESEARCH LEADERSHIP: Israel prioritized science. Kenya's universities could become Africa's cannabis research hub with proper investment.

2. PHARMACEUTICAL FOCUS: Medical-grade exports are more valuable than recreational. Kenya could target European medical markets.

3. TECH INNOVATION: Israeli startups created cultivation tech, testing equipment, apps. Kenya tech sector could develop African-specific solutions.

4. PATIENT-CENTERED POLICY: Focus on compassionate use builds public support. Start with medical to prove safety and efficacy.

5. EXPORT STRATEGY: GMP certification and quality standards open international markets. Kenya should pursue EU-GMP from day one.

6. GOVERNMENT COORDINATION: IMCA provides centralized oversight while enabling innovation. Kenya needs a dedicated cannabis authority.""",
            
            'annual_revenue': '$300+ Million (Medical)'
        },
        
        'uruguay': {
            'detailed_history': """Uruguay became the first country in the world to fully legalize recreational cannabis on December 10, 2013, when President José Mujica signed Law 19.172. The goal was to undermine drug trafficking and reduce harm.

The law created a unique state-controlled model: citizens can grow at home (up to 6 plants), join cannabis clubs (up to 99 members, 45 plants), or purchase from licensed pharmacies. Foreigners cannot buy cannabis.

Implementation was slow—pharmacy sales didn't begin until 2017—but the system is now mature. The Institute for the Regulation and Control of Cannabis (IRCCA) oversees all activities. Prices are deliberately set low ($1.30/gram) to undercut the black market.""",
            
            'timeline': """• 2012: Bill introduced to parliament
• December 2013: Law 19.172 signed by President Mujica
• 2014: IRCCA (regulatory body) established
• 2014: Home cultivation permits begin
• 2015: Cannabis clubs registered
• 2017: Pharmacy sales finally begin
• 2019: 50,000+ registered users
• 2021: 70,000+ registered buyers
• 2022: ~80% of market is legal (vs 30% initially)
• 2023: Prices stable at ~$1.30/gram""",
            
            'economic_impact': """• Deliberately non-commercial model prioritizes public health
• $22 million in annual pharmacy sales (2023)
• Black market reduced from 70% to ~20% of consumption
• $30 million saved annually in enforcement costs
• Zero cannabis-related drug trafficking violence
• 500+ hectares under licensed cultivation
• Export to other countries not emphasized
• No cannabis tourism (foreigners cannot buy)
• 40,000+ home growers registered
• 200+ cannabis clubs operating legally""",
            
            'lessons_for_kenya': """1. PUBLIC HEALTH FOCUS: Uruguay prioritized harm reduction over revenue. This approach builds broad political support.

2. PRICE CONTROLS: $1.30/gram deliberately undercuts black market. Kenya must ensure legal cannabis is affordable.

3. MULTIPLE ACCESS PATHS: Home grow, clubs, and pharmacy sales give options. Kenya could offer similar flexibility.

4. PATIENT APPROACH: Slow implementation (4 years to full rollout) prevented major problems. Kenya should not rush.

5. STATE CONTROL: Government controls production and sets prices. Kenya could have a hybrid model with private cultivation but government pricing oversight.

6. NO ADVERTISING: Zero cannabis advertising allowed. Maintains public health focus and reduces controversy.""",
            
            'annual_revenue': '$22 Million (State-controlled)'
        },
        
        'germany': {
            'detailed_history': """Germany legalized recreational cannabis on April 1, 2024, becoming the largest European country to do so. The Cannabis Act (CanG) was passed by the Bundestag in February 2024 after years of coalition negotiations.

The law allows adults 18+ to possess up to 25 grams in public (50g at home) and grow up to 3 plants. Commercial sales will begin through "cannabis clubs" (non-profit associations of up to 500 members) starting July 2024.

Medical cannabis was legalized in 2017, and Germany quickly became Europe's largest medical cannabis market, importing heavily from Canada, Netherlands, and Portugal. The recreational market is expected to be worth €3.5 billion annually.""",
            
            'timeline': """• 2017: Medical cannabis legalized (covered by insurance)
• 2019: Germany becomes Europe's largest medical market
• 2021: "Traffic light" coalition promises legalization
• 2023: Draft Cannabis Act released
• February 2024: Bundestag passes Cannabis Act
• April 1, 2024: Possession and home growing legal
• July 2024: Cannabis clubs can begin operations
• 2025: Potential pilot program for commercial sales
• Target: Commercial retail in some regions by 2026""",
            
            'economic_impact': """• Medical market: €500 million+ annually
• Projected recreational market: €3.5 billion annually
• Estimated 60,000 new jobs
• €4.7 billion in tax revenue projected (full legalization)
• Over 400,000 medical cannabis patients
• Major importer: Canada, Netherlands, Portugal, Israel
• Pharmaceutical investment hub in Europe
• Commercial cultivation expansion planned
• Potential EU export hub
• Savings of €1 billion annually in enforcement""",
            
            'lessons_for_kenya': """1. COALITION BUILDING: Legalization required agreement across political parties. Kenya needs cross-party support.

2. MEDICAL FIRST: Germany's successful medical program (since 2017) built public acceptance before recreational legalization.

3. INSURANCE COVERAGE: Medical cannabis covered by health insurance. Kenya's NHIF could include coverage for eligible patients.

4. EU COMPLIANCE: Germany navigated complex EU regulations. Kenya should consider AU/EAC frameworks.

5. CLUB MODEL: Non-profit cannabis clubs reduce commercialization concerns. Kenya could pilot similar community-based access.

6. IMPORT STRATEGY: Germany imports most cannabis. Kenya could become a supplier to European markets.""",
            
            'annual_revenue': '€500 Million+ (Medical, growing)'
        },
        
        'south-africa': {
            'detailed_history': """South Africa's Constitutional Court ruled in September 2018 (Minister of Justice and Constitutional Development v Prince) that the prohibition of private cultivation and use of cannabis was unconstitutional. Adults can now grow and consume cannabis at home.

However, buying, selling, and public use remain illegal. This creates a legal gray area—you can grow but cannot legally obtain seeds or sell any harvest. Medical cannabis was regulated separately in 2017 under SAHPRA (SA Health Products Regulatory Authority).

The Private Member's Bill to regulate commercial cannabis (proposed 2020) has stalled in Parliament. Meanwhile, a thriving gray market of "gifting" and private clubs has emerged.""",
            
            'timeline': """• 2017: SAHPRA begins licensing medical cannabis
• September 2018: Constitutional Court ruling (Prince case)
• 2018: Private use and cultivation legalized
• 2019: Traditional uses (Rastafari) recognized
• 2020: Private Member's Cannabis Bill introduced
• 2021: Cannabis Master Plan announced
• 2022: KwaZulu-Natal hemp pilot projects
• 2023: Medical and hemp exports begin
• 2024: Full commercial framework still pending
• Eastern Cape emerges as cultivation hub""",
            
            'economic_impact': """• $1.8 billion estimated (mostly informal market)
• 900,000+ regular cannabis users
• Medical/hemp exports: $5+ million (2023)
• 1,000+ hectares of licensed hemp cultivation
• 50+ medical cannabis facility licenses
• 10,000+ jobs in informal cannabis economy
• Eastern Cape: historical cannabis farming region
• Potential legal market: $2-3 billion annually
• Dagga private clubs (hundreds nationwide)
• Cannabis tourism emerging in Cape Town""",
            
            'lessons_for_kenya': """1. CONSTITUTIONAL APPROACH: Court-led reform can bypass political gridlock. Kenya's courts could similarly interpret constitutional rights.

2. DECRIMINALIZATION AS STEP ONE: Private use/cultivation first, commercial regulation later. Kenya could follow this phased approach.

3. INDIGENOUS KNOWLEDGE: SA recognized traditional/Rastafari use. Kenya should include traditional healing practitioners.

4. HEMP FIRST: Hemp licensing moved faster than recreational. Kenya could prioritize industrial hemp.

5. IMPLEMENTATION GAPS: SA's lack of commercial framework creates confusion. Kenya must have comprehensive rules ready.

6. REGIONAL LEADERSHIP: As Africa's largest economy, SA influences the continent. Kenya could lead East Africa similarly.""",
            
            'annual_revenue': '$1.8 Billion (estimated, mostly informal)'
        },
        
        'lesotho': {
            'detailed_history': """Lesotho made history in 2017 as the first African country to grant a license for medical cannabis cultivation. The landlocked mountain kingdom, one of Africa's smallest and poorest nations, saw cannabis as an economic opportunity.

Mophato wa Bophelo, a joint venture with Canadian company Supreme Cannabis, received the first license. By 2023, over 15 licensed producers operate in the country, primarily for export to markets in Europe, Australia, and South Africa.

The Cannabis and Hemp Bill (2023) aims to create a comprehensive regulatory framework. Lesotho's unique climate (clean air, high altitude, cheap labor) makes it ideal for organic cultivation.""",
            
            'timeline': """• 2017: First medical cannabis license issued (Mophato wa Bophelo)
• 2018: Additional cultivation licenses granted
• 2019: First legal exports to Canada
• 2020: Expanded licensing framework
• 2021: 10+ licensed producers operating
• 2022: EU-GMP certified facilities opened
• 2023: Cannabis and Hemp Bill drafted
• 2023: Exports to 15+ countries
• 2024: Focus on EU market access
• Target: $1 billion industry by 2030""",
            
            'economic_impact': """• $30+ million in licensed production (2023)
• 15+ licensed cannabis producers
• 5,000+ jobs created in legal sector
• Traditional cultivation: 50+ years in highlands
• Export destinations: Canada, UK, Germany, Australia
• 3 EU-GMP certified production facilities
• Average wage: 3x local minimum wage
• Foreign direct investment: $200+ million
• Community projects funded by operators
• Agricultural diversification from declining textile sector""",
            
            'lessons_for_kenya': """1. FIRST MOVER ADVANTAGE: Being first in Africa attracted significant investment. Kenya can still be an East African leader.

2. EXPORT FOCUS: Lesotho built for international markets first. Kenya should pursue GMP certification from the start.

3. JOINT VENTURES: Partnering with experienced international companies brought capital and expertise. Kenya should welcome foreign investment.

4. COMMUNITY INVOLVEMENT: Licensed producers must hire locally and fund community projects. Kenya should mandate similar requirements.

5. CLIMATE ADVANTAGE: Lesotho marketed its unique growing conditions. Kenya has multiple ideal microclimates (Nyeri, Meru, Nyandarua).

6. REGULATORY SPEED: Quick licensing attracted investment. Kenya must balance speed with proper oversight.""",
            
            'annual_revenue': '$30+ Million (export-focused)'
        }
    }
    
    for slug, data in country_data.items():
        evidence = ManifestoEvidence.objects.filter(slug=slug).first()
        if evidence:
            evidence.detailed_history = data.get('detailed_history', '')
            evidence.timeline = data.get('timeline', '')
            evidence.economic_impact = data.get('economic_impact', '')
            evidence.lessons_for_kenya = data.get('lessons_for_kenya', '')
            if data.get('annual_revenue'):
                evidence.annual_revenue = data['annual_revenue']
            evidence.save()


def reverse_populate(apps, schema_editor):
    # Optionally clear the data if migration is reversed
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_blogpost_cropping'),
    ]

    operations = [
        migrations.RunPython(populate_country_data, reverse_populate),
    ]
