# Generated by Django 6.0 on 2026-01-15 23:44

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_populate_cannabis_country_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '1200x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
