# Generated by Django 6.0 on 2026-01-16 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_carouselimage_cropping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='core.county')),
            ],
            options={
                'verbose_name_plural': 'Constituencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MPCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, help_text='Candidate Photo', null=True, upload_to='mp_candidates/')),
                ('description', models.TextField(blank=True, help_text='Short bio or description')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo link', null=True)),
                ('manifesto', models.TextField(blank=True, help_text="Candidate's specific manifesto for the constituency")),
                ('social_handle_twitter', models.CharField(blank=True, max_length=100)),
                ('social_handle_facebook', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='core.constituency')),
            ],
        ),
    ]
