# Generated by Django 6.0 on 2026-01-16 08:58

import ckeditor.fields
import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_constituency_mpcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpcandidate',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('profile_image', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop for optimal display (Square)', hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='mpcandidate',
            name='manifesto',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Candidate's specific manifesto for the constituency"),
        ),
    ]
