# Generated by Django 6.0 on 2026-01-16 09:58

import django.db.models.deletion
import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_mpcandidate_cropping_alter_mpcandidate_manifesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('president', 'President'), ('governor', 'Governor'), ('senator', 'Senator'), ('woman_rep', 'Woman Representative'), ('mp', 'Member of Parliament'), ('mca', 'Member of County Assembly')], default='mp', max_length=20)),
                ('ward', models.CharField(blank=True, help_text='Required for MCA', max_length=200)),
                ('profile_image', models.ImageField(blank=True, help_text='Candidate Photo', null=True, upload_to='aspirants/')),
                ('cropping', image_cropping.fields.ImageRatioField('profile_image', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop for optimal display (Square)', hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('description', models.TextField(blank=True, help_text='Short bio or description')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo link', null=True)),
                ('manifesto', models.TextField(blank=True, help_text="Candidate's specific manifesto")),
                ('social_handle_twitter', models.CharField(blank=True, max_length=100)),
                ('social_handle_facebook', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constituency', models.ForeignKey(blank=True, help_text='Required for MP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspirants', to='core.constituency')),
                ('county', models.ForeignKey(blank=True, help_text='Required for Governor, Senator, Woman Rep', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspirants', to='core.county')),
            ],
            options={
                'ordering': ['role', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='MPCandidate',
        ),
    ]
