# Generated by Django 6.0 on 2026-01-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_aspirant_delete_mpcandidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for identification', max_length=100)),
                ('image', models.ImageField(help_text='Use transparent PNG for best results', upload_to='floating/')),
                ('position', models.CharField(choices=[('hero_right', 'Hero Section (Right)'), ('hero_left', 'Hero Section (Left)')], default='hero_right', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
