# Generated by Django 6.0 on 2026-01-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_floatingimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='role',
            field=models.CharField(choices=[('president', 'President'), ('governor', 'Governor'), ('senator', 'Senator'), ('woman_rep', 'Woman Representative'), ('mp', 'Member of Parliament'), ('mca', 'Member of County Assembly')], db_index=True, default='mp', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('news', 'Party News'), ('press', 'Press Release'), ('campaign', 'Campaign Update'), ('policy', 'Policy Announcement'), ('event', 'Event Recap'), ('opinion', 'Opinion')], db_index=True, default='news', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Show on homepage'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
