# Generated by Django 6.0 on 2026-01-25 14:04

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_aspirant_is_active_alter_aspirant_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Main party logo displayed on homepage and throughout the site', null=True, upload_to='site/logo/')),
                ('logo_cropping', image_cropping.fields.ImageRatioField('logo', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop the logo for optimal display (square format recommended)', hide_image_field=False, size_warning=False, verbose_name='logo cropping')),
                ('logo_square', models.ImageField(blank=True, help_text='Square version of logo (for favicons, social media, etc.)', null=True, upload_to='site/logo/')),
                ('site_name', models.CharField(default='Roots Party', help_text='Official site name', max_length=200)),
                ('site_tagline', models.CharField(blank=True, default='TINGIZA MTI!', help_text='Site tagline/slogan', max_length=300)),
                ('contact_email', models.EmailField(blank=True, help_text='Primary contact email', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Primary contact phone', max_length=20)),
                ('twitter_handle', models.CharField(blank=True, help_text='Twitter handle (without @)', max_length=100)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
