# Generated by Django 6.0 on 2026-01-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='carousel_duration',
            field=models.IntegerField(default=8000, help_text='Carousel image duration in milliseconds (default: 8000 = 8 seconds). Minimum: 2000ms (2 seconds)'),
        ),
    ]
