# Generated by Django 5.2.10 on 2026-02-07 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_add_carousel_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspirantRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, verbose_name='ID Number')),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=200)),
                ('phone_number', models.CharField(help_text='Used for verification and notifications', max_length=20)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address (Optional)')),
                ('position', models.CharField(choices=[('governor', 'Governor - KES 10,000'), ('senator', 'Senator - KES 5,000'), ('woman_rep', 'Woman Representative - KES 5,000'), ('mp', 'Member of Parliament (MP) - KES 5,000'), ('mca', 'Member of County Assembly (MCA) - KES 2,000')], max_length=50, verbose_name='Select Position')),
                ('is_incumbent', models.BooleanField(default=False, verbose_name='Are you a current elected leader?')),
                ('membership_status', models.CharField(choices=[('existing', 'Existing Roots Party Member'), ('new', 'New Member')], default='new', max_length=20, verbose_name='Party Membership Status')),
                ('agreed_to_terms', models.BooleanField(default=False, verbose_name='I agree to the Terms and Conditions')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aspirant Application',
                'verbose_name_plural': 'Aspirant Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='carousel_duration',
            field=models.IntegerField(default=8000, help_text='Carousel image duration in milliseconds (default: 8000 = 8 seconds). Minimum: 2000ms (2 seconds)', validators=[django.core.validators.MinValueValidator(2000)]),
        ),
    ]
