# Generated by Django 5.2.10 on 2026-02-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_aspirantregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirantregistration',
            name='draft_token',
            field=models.CharField(blank=True, help_text='Token for resuming draft applications', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='aspirantregistration',
            name='photo',
            field=models.ImageField(blank=True, help_text='Passport photo (JPG/PNG, max 2MB)', null=True, upload_to='aspirants/photos/'),
        ),
        migrations.AddField(
            model_name='aspirantregistration',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft - Incomplete'), ('submitted', 'Submitted - Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='aspirantregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aspirantregistration',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aspirantregistration',
            name='position',
            field=models.CharField(blank=True, choices=[('governor', 'Governor - KES 10,000'), ('senator', 'Senator - KES 5,000'), ('woman_rep', 'Woman Representative - KES 5,000'), ('mp', 'Member of Parliament (MP) - KES 5,000'), ('mca', 'Member of County Assembly (MCA) - KES 2,000')], max_length=50, verbose_name='Select Position'),
        ),
    ]
