# Generated by Django 5.2.10 on 2026-02-07 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_aspirantregistration_draft_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirantregistration',
            name='constituency',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Target Constituency'),
        ),
        migrations.AddField(
            model_name='aspirantregistration',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.county', verbose_name='Target County'),
        ),
        migrations.AddField(
            model_name='aspirantregistration',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Target Ward'),
        ),
    ]
