# Generated by Django 5.2.10 on 2026-02-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_aspirantregistration_constituency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirantregistration',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Check this to mark the aspirant as verified.', verbose_name='Verified Aspirant'),
        ),
    ]
