# Generated by Django 5.2.10 on 2026-02-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_aspirantregistration_is_verified'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aspirantregistration',
            index=models.Index(fields=['id_number'], name='core_aspira_id_numb_1908ed_idx'),
        ),
        migrations.AddIndex(
            model_name='aspirantregistration',
            index=models.Index(fields=['position'], name='core_aspira_positio_27a5b2_idx'),
        ),
        migrations.AddIndex(
            model_name='aspirantregistration',
            index=models.Index(fields=['county'], name='core_aspira_county__d924dc_idx'),
        ),
        migrations.AddIndex(
            model_name='aspirantregistration',
            index=models.Index(fields=['is_verified'], name='core_aspira_is_veri_588738_idx'),
        ),
        migrations.AddIndex(
            model_name='aspirantregistration',
            index=models.Index(fields=['created_at'], name='core_aspira_created_984b19_idx'),
        ),
        migrations.AddIndex(
            model_name='aspirantregistration',
            index=models.Index(fields=['status', 'created_at'], name='core_aspira_status_66ffea_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_published', 'created_at'], name='core_blogpo_is_publ_fc2b5a_idx'),
        ),
    ]
