# Generated by Django 5.2.10 on 2026-02-08 20:00
# Edited: use SeparateDatabaseAndState so we do not drop tables (models moved to aspirants app, same DB tables).

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_aspirantregistration_core_aspira_id_numb_1908ed_idx_and_more'),
    ]

    operations = [
        # Remove aspirant/leadership/aspirantregistration from core *state* only (tables stay; used by aspirants app).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='aspirant',
                    name='constituency',
                ),
                migrations.RemoveField(
                    model_name='aspirant',
                    name='county',
                ),
                migrations.RemoveField(
                    model_name='aspirantregistration',
                    name='county',
                ),
                migrations.DeleteModel(
                    name='LeadershipRole',
                ),
                migrations.DeleteModel(
                    name='Aspirant',
                ),
                migrations.DeleteModel(
                    name='AspirantRegistration',
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '1200x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop for carousel display', hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
