# Generated by Django 5.2.10 on 2026-02-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_aspirant_constituency_remove_aspirant_county_and_more'),
    ]

    def convert_timeline_to_json(apps, schema_editor):
        ManifestoEvidence = apps.get_model('core', 'ManifestoEvidence')
        for item in ManifestoEvidence.objects.all():
            if not item.timeline or item.timeline.strip() == '':
                item.timeline = '{}'
                item.save()

    operations = [
        migrations.RunPython(convert_timeline_to_json, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='manifestoevidence',
            name='timeline',
            field=models.JSONField(blank=True, default=dict, help_text='Key dates and milestones'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
