# Generated by Django 5.2.10 on 2026-02-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_aspirant_constituency_remove_aspirant_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestoevidence',
            name='timeline',
            field=models.JSONField(blank=True, default=dict, help_text='Key dates and milestones'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
