# Generated by Django 5.2.10 on 2026-02-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_manifestoevidence_timeline_delete_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Splash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Main Splash Screen', help_text='Internal name for this splash screen', max_length=100)),
                ('image', models.ImageField(help_text='Upload the splash screen image', upload_to='site/splash/')),
                ('is_active', models.BooleanField(default=True, help_text='Only one active splash screen will be shown')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Splash Screen',
                'verbose_name_plural': 'Splash Screens',
                'ordering': ['-updated_at'],
            },
        ),
    ]
