# Generated by Django 5.2.10 on 2026-02-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_splash'),
    ]

    operations = [
        migrations.AddField(
            model_name='splash',
            name='animation',
            field=models.CharField(choices=[('palpating', 'Palpating (Pulse)'), ('spinning', 'Spinning'), ('reveal', 'Logo Reveal (Fade & Scale)'), ('floating', 'Floating')], default='reveal', help_text='Select the animation for the logo', max_length=20),
        ),
    ]
