# Generated by Django 5.2.10 on 2026-02-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_splash_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='description',
            field=models.TextField(blank=True, help_text='Secondary content area or detailed description'),
        ),
    ]
