# Generated by Django 5.2.10 on 2026-02-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_pagecontent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='splash',
            name='logo_width',
            field=models.IntegerField(default=450, help_text='Target width of the logo in pixels. The image will be automatically resized and optimized on upload.'),
        ),
    ]
