# Generated by Django 5.2.10 on 2026-02-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_event_uuid_alter_gatepass_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='gate_passes/'),
        ),
    ]
