# Generated by Django 5.2.10 on 2026-02-14 08:39

import django_ckeditor_5.fields
import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_partyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('intro', models.TextField(help_text='Short drop-cap introduction')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('color_class', models.CharField(help_text='Tailwind class e.g. text-roots-green', max_length=50)),
                ('icon', models.TextField(help_text='SVG code for the icon')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Tribe',
                'verbose_name_plural': 'Tribes',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '800x450', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text='Crop for optimal display (default 16:9, but flexible)', hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
