# Generated by Django 5.2.10 on 2026-02-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_tribe_alter_blogpost_cropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='image',
            field=models.ImageField(blank=True, help_text='Featured image for the tribe page', null=True, upload_to='tribes/'),
        ),
    ]
