# Generated by Django 5.2.10 on 2026-02-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_tribe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe',
            name='content',
            field=models.TextField(help_text='Full letter content'),
        ),
    ]
