# Generated by Django 5.2.10 on 2026-02-14 09:14

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_tribe_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '800x450', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text='Crop for optimal display', hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
