# Generated by Django 6.0.2 on 2026-03-06 13:22

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_tribe_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Full letter content'),
        ),
    ]
