# Generated by Django 5.2.10 on 2026-02-09 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('fake_product', 'Fake/Counterfeit Product'), ('wrong_price', 'Incorrect Price'), ('unresponsive', 'Unresponsive/Delayed Response'), ('scam', 'Potential Scam/Fraud'), ('inappropriate', 'Inappropriate Content/Language'), ('other', 'Other Issue')], max_length=50)),
                ('description', models.TextField()),
                ('email', models.EmailField(blank=True, help_text='Optional: Your email for follow-up', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='commerce.vendor')),
            ],
            options={
                'db_table': 'core_vendor_report',
                'ordering': ['-created_at'],
            },
        ),
    ]
