# Generated by Django 5.2.10 on 2026-02-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_vendorreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('business_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(help_text='Where is your business based?', max_length=200)),
                ('product_categories', models.CharField(help_text='e.g., Apparel, Art, Accessories, CBD', max_length=300)),
                ('business_description', models.TextField(help_text='Describe what you sell and how it aligns with Roots Party values.')),
                ('social_links', models.TextField(blank=True, help_text='Links to your Instagram, Twitter, or Website')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes from party leadership')),
            ],
            options={
                'db_table': 'core_vendor_application',
                'ordering': ['-created_at'],
            },
        ),
    ]
