# Generated by Django 5.2.10 on 2026-02-09 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_vendorapplication'),
        ('core', '0045_alter_manifestoevidence_timeline_delete_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorapplication',
            name='constituency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.county'),
        ),
        migrations.AddField(
            model_name='vendorapplication',
            name='ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vendorapplication',
            name='location',
            field=models.CharField(help_text='Specific Address or Market (e.g. River Road, Cara House)', max_length=200),
        ),
    ]
