# Generated by Django 5.2.10 on 2026-02-08 20:00
# Edited: state-only migration so we do not create tables (reuse core_* tables from core app).

import django.db.models.deletion
import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0044_remove_aspirant_constituency_remove_aspirant_county_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='LeadershipRole',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=200)),
                        ('slug', models.SlugField(help_text='URL identifier e.g. president, governor', unique=True)),
                        ('icon_svg_path', models.TextField(help_text='Paste the SVG path data (d attribute) here')),
                        ('description', models.TextField(help_text='Main role description')),
                        ('responsibilities', models.TextField(help_text='Enter each responsibility on a new line')),
                        ('roots_context', models.TextField(help_text='The Roots Mandate for this role')),
                        ('prospects', models.TextField(blank=True, help_text='Why a Roots Government? Enter each point on a new line')),
                        ('candidate_name', models.CharField(blank=True, help_text='Name of the current candidate/holder', max_length=200)),
                        ('image', models.ImageField(blank=True, help_text='Candidate photo', null=True, upload_to='leadership/')),
                        ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo link for candidate message', null=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'db_table': 'core_leadershiprole',
                    },
                ),
                migrations.CreateModel(
                    name='Aspirant',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=200)),
                        ('role', models.CharField(choices=[('president', 'President'), ('governor', 'Governor'), ('senator', 'Senator'), ('woman_rep', 'Woman Representative'), ('mp', 'Member of Parliament'), ('mca', 'Member of County Assembly')], db_index=True, default='mp', max_length=20)),
                        ('ward', models.CharField(blank=True, help_text='Required for MCA', max_length=200)),
                        ('profile_image', models.ImageField(blank=True, help_text='Candidate Photo', null=True, upload_to='aspirants/')),
                        ('cropping', image_cropping.fields.ImageRatioField('profile_image', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Crop for optimal display (Square)', hide_image_field=False, size_warning=False, verbose_name='cropping')),
                        ('description', models.TextField(blank=True, help_text='Short bio or description')),
                        ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo link', null=True)),
                        ('manifesto', models.TextField(blank=True, help_text="Candidate's specific manifesto")),
                        ('social_handle_twitter', models.CharField(blank=True, max_length=100)),
                        ('social_handle_facebook', models.CharField(blank=True, max_length=100)),
                        ('is_active', models.BooleanField(db_index=True, default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('constituency', models.ForeignKey(blank=True, help_text='Required for MP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspirant_profiles', to='core.constituency')),
                        ('county', models.ForeignKey(blank=True, help_text='Required for Governor, Senator, Woman Rep', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aspirant_profiles', to='core.county')),
                    ],
                    options={
                        'db_table': 'core_aspirant',
                        'ordering': ['role', 'name'],
                    },
                ),
                migrations.CreateModel(
                    name='AspirantRegistration',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('id_number', models.CharField(max_length=20, verbose_name='ID Number')),
                        ('surname', models.CharField(max_length=100)),
                        ('other_names', models.CharField(max_length=200)),
                        ('phone_number', models.CharField(help_text='Used for verification and notifications', max_length=20)),
                        ('date_of_birth', models.DateField(blank=True, null=True)),
                        ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address (Optional)')),
                        ('photo', models.ImageField(blank=True, help_text='Passport photo (JPG/PNG, max 2MB)', null=True, upload_to='aspirants/photos/')),
                        ('position', models.CharField(blank=True, choices=[('governor', 'Governor - KES 10,000'), ('senator', 'Senator - KES 5,000'), ('woman_rep', 'Woman Representative - KES 5,000'), ('mp', 'Member of Parliament (MP) - KES 5,000'), ('mca', 'Member of County Assembly (MCA) - KES 2,000')], max_length=50, verbose_name='Select Position')),
                        ('constituency', models.CharField(blank=True, max_length=100, null=True, verbose_name='Target Constituency')),
                        ('ward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Target Ward')),
                        ('is_incumbent', models.BooleanField(default=False, verbose_name='Are you a current elected leader?')),
                        ('membership_status', models.CharField(choices=[('existing', 'Existing Roots Party Member'), ('new', 'New Member')], default='new', max_length=20, verbose_name='Party Membership Status')),
                        ('agreed_to_terms', models.BooleanField(default=False, verbose_name='I agree to the Terms and Conditions')),
                        ('status', models.CharField(choices=[('draft', 'Draft - Incomplete'), ('submitted', 'Submitted - Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=20)),
                        ('draft_token', models.CharField(blank=True, help_text='Token for resuming draft applications', max_length=64, null=True, unique=True)),
                        ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                        ('is_verified', models.BooleanField(default=False, help_text='Check this to mark the aspirant as verified.', verbose_name='Verified Aspirant')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.county', verbose_name='Target County')),
                    ],
                    options={
                        'verbose_name': 'Aspirant Application',
                        'verbose_name_plural': 'Aspirant Applications',
                        'db_table': 'core_aspirantregistration',
                        'ordering': ['-created_at'],
                        'indexes': [models.Index(fields=['id_number'], name='core_aspira_id_numb_1908ed_idx'), models.Index(fields=['position'], name='core_aspira_positio_27a5b2_idx'), models.Index(fields=['county'], name='core_aspira_county__d924dc_idx'), models.Index(fields=['is_verified'], name='core_aspira_is_veri_588738_idx'), models.Index(fields=['created_at'], name='core_aspira_created_984b19_idx'), models.Index(fields=['status', 'created_at'], name='core_aspira_status_66ffea_idx')],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
