# Generated by Django 5.2.10 on 2026-02-08 22:22

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspirants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirant',
            name='manifesto',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="Candidate's specific manifesto"),
        ),
    ]
