# Generated by Django 5.2.10 on 2026-02-11 22:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirants', '0002_alter_aspirant_manifesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirant',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='aspirantregistration',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
