# Generated by Django 5.2.10 on 2026-02-11 22:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirants', '0003_aspirant_uuid_aspirantregistration_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirant',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='aspirantregistration',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
