# Generated by Django 5.2.10 on 2026-02-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirants', '0004_alter_aspirant_uuid_alter_aspirantregistration_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirantregistration',
            name='profile_pdf',
            field=models.FileField(blank=True, null=True, upload_to='aspirants/profiles/'),
        ),
    ]
